name: Add Escalations to Project

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    if: contains(github.event.issue.labels.*.name, 'escalation')
    runs-on: ubuntu-latest
    
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/footballguysdotcom/projects/5
          github-token: ${{ secrets.GITHUB_TOKEN }}

